export const GAME_WIDTH = 1600;
export const GAME_HEIGHT = 900;

export const DEFAULT_LIVES = 3;

export const DEFAULT_STARTING_CIRCLE_RADIUS = 400;
export const DEFAULT_STARTING_SPAWN_SPEED = 900;
export const DEFAULT_STARTING_SHRINK_SPEED = 0.015;

export const DEFAULT_SCORE_GAIN = 5;
export const DEFAULT_MISCLICK_DEDUCTION = -20;
export const DEFAULT_LOW_SCORE_LOSS = -20;

export const CIRCLE_MININUM_SCALED_SIZE = 0.05;

export const CIRCLE_RADIUS_SHRINK_TICK_RATE = 50;
export const CIRCLE_RADIUS_RATE_DECREASE_TICK_RATE = 7000;
export const CIRCLE_SPAWN_SPEED_RATE_DECREASE_TICK_RATE = 2000;
export const CIRCLE_SHRINK_SPEED_RATE_DECREASE_TICK_RATE = 25000;

export const CIRCLE_RADIUS_MININUM_LIMIT = 210;
export const CIRCLE_SPAWN_SPEED_MININUM_LIMIT = 290;
export const CIRCLE_SHRINK_SPEED_MININUM_LIMIT = 0.025;

export const CIRCLE_RADIUS_CHANGE = -15;
export const CIRCLE_SPAWN_SPEED_CHANGE = -25;
export const CIRCLE_SHRINK_SPEED_CHANGE = 0.005;
